# Generated by Django 5.2.3 on 2025-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='waktu',
            new_name='tanggal',
        ),
        migrations.AlterField(
            model_name='itemtransaksi',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
